### ISSUE TITLE
ActionAttempt.php Error

### ISSUE THREAD

**Issue by rguerin1** [seamapi/php#88]
I get the following error when trying to lock a door using the example code.     Any help would be greatly appreciated.

Fatal error: Uncaught TypeError: Seam\Objects\ActionAttempt::__construct(): Argument #4 ($result) must be of type ?string, stdClass given, called in /home/qa43mss75pl2/public_html/app.webbids.net/Seam/vendor/seamapi/seam/src/Objects/ActionAttempt.php on line 13 and defined in /home/qa43mss75pl2/public_html/app.webbids.net/Seam/vendor/seamapi/seam/src/Objects/ActionAttempt.php:24 Stack trace: #0 /home/qa43mss75pl2/public_html/app.webbids.net/Seam/vendor/seamapi/seam/src/Objects/ActionAttempt.php(13): Seam\Objects\ActionAttempt->__construct() #1 /home/qa43mss75pl2/public_html/app.webbids.net/Seam/vendor/seamapi/seam/src/SeamClient.php(597): Seam\Objects\ActionAttempt::from_json() #2 /home/qa43mss75pl2/public_html/app.webbids.net/Seam/vendor/seamapi/seam/src/SeamClient.php(629): Seam\ActionAttemptsClient->get() #3 /home/qa43mss75pl2/public_html/app.webbids.net/Seam/vendor/seamapi/seam/src/SeamClient.php(1586): Seam\ActionAttemptsClient->poll_until_ready() #4 /home/qa43mss75pl2/public_html/app.webbids.net/Seam/test3.php(20): Seam\LocksClient->lock_door() #5 {main} thrown in /home/qa43mss75pl2/public_html/app.webbids.net/Seam/vendor/seamapi/seam/src/Objects/ActionAttempt.php on line 24

**Comment by seveibar** [comment]
Hey @rguerin1, we'll look into this, in the meantime can you try using version 1? `composer require seamapi/seam@1.1`

**Comment by seveibar** [comment]
If you go to https://console.seam.co and put a question into our intercom chat mentioning this issue and pass along a uuid, we can debug a bit more specifically.

For our engineerings, here is the test: https://github.com/seamapi/php/blob/main/tests/ActionAttemptsTest.php

**Comment by rguerin1** [comment]
Before you emailed I did try version 1.1 and there were no issues.    I got
version 1.1 by downloading the zip file.    I just hadn't had time to
comment on that yet.     What is the uuid that you are wanting?    I'm a
little new to this and would love to help you out.   The ActionAttempt.php
file is definitely different between the two versions.    I installed the
version composer downloads on Tuesday of this week.    That was the one
that has an issue.

Robert

**Comment by NicTorgersen** [comment]
@seveibar Please tag v2.0.1 soon, so we don't have to manually patch this or use dev-main.
